### ISSUE TITLE
Unable to map through types and assign to a field

### ISSUE THREAD

**Issue by SamScott3000** [saiichihashimoto/sanity-typed#111] opened 2023-07-05 12:25 UTC
Passing in a mapped array of `ArrayMembers` causes this error:

```
  Source provides no match for required element at position 0 in target.
```

Whereas using a literal is fine

```ts
import quote from "./quote";
import ticker from "./ticker";

const allComponents = [quote, ticker];

const mappedArray = allComponents.map(component => 
  defineArrayMember({
    name: component.name,
    type: component.name,
  }),
);

const normalArray = [ // <-- working fine
  defineArrayMember({
    name: quote.name,
    type: quote.name,
  }),
  defineArrayMember({
    name: ticker.name,
    type: ticker.name,
  }),
] as const;

export const allComponentsField = defineField({
  name: "components",
  title: "Components",
  type: "array",

  of: [...normalArray],
  // of: [...mappedArray], <-- Throws error
});
```

Changing:
```ts
of: [TMemberDefinition, ...TMemberDefinition[]]
``` 

to:
```ts
of: TMemberDefinition[]
```

in the array type fixes this, but there are probably knock on negative effects to making this change.

**Comment by saiichihashimoto** [comment] 2023-07-05 22:28
So `of` requires a tuple of at least length one, because sanity requires this. `mappedArray` is just an array as opposed to `normalArray` being a tuple. Having the types match the reality as well as possible is a good idea. It could be argued that this library's goal is to create the derived sanity value types, not add new restrictions. I think it's worth it to do this, because having typescript enforce the same things runtime will enforce will correct issues before you even run sanity.

That being said, I'm sure you'll run into arrays/tuples again somewhere, so here's some issues I'm seeing with your current implementation:

- Is `allComponents` being typed as a tuple or an array? Not sure how that works.

<img width="645" alt="image" src="https://github.com/saiichihashimoto/sanity-typed/assets/2819256/9993e0ee-fc0d-4ba0-944f-2efcbad1af20">

- Mapping tuples has issues in typescript, although there are workarounds. Making `of` require an array instead of a tuple would avoid these issues, but the issue isn't that the library is typed wrong but, rather, that typescript doesn't have a good solution for this. I'd prefer people use the workaround rather than changing the library to a less correct type.

I'm going to close this, as it's not an issue with the library but rather a difficulty with typescript.

**Closed by saiichihashimoto** 2023-07-05 22:28 UTC

**Comment by SamScott3000** [comment] 2023-07-06 12:01
Thanks for the help. A messy solution for reference if needed.

```ts
declare global {
  interface Array<T> {
    map<U>(
      callbackfn: (value: T, index: number, tuple: T[] | [T]) => U,
      thisArg?: any,
    ): { [K in keyof this]: U };
  }
}

type DeepMutable<T> = { -readonly [P in keyof T]: DeepMutable<T[P]> };
const allComponents = [quote, ticker] as const;

const mutableComponents = allComponents as DeepMutable<typeof allComponents>;

const mappedArray = mutableComponents.map(component => {
  return defineArrayMember({
    name: component.name,
    type: component.name,
  });
});

export const allComponentsField = defineField({
  name: "components",
  title: "Components",
  type: "array",
  of: mappedArray,
});
```
