### ISSUE TITLE
Type Error on validation method

### ISSUE THREAD

**Issue by mckelveygreg** [saiichihashimoto/sanity-typed#63] opened 2023-06-14 05:01 UTC
Hey! Just noticed the transition to more of a types focus and that's awesome! 
I just ran into an issue where I'm not able to use different Rule methods beyond `.required()`. I tried to crack it open, but I wasn't sure where / able to help the types narrow to the `RuleDef`'s for each schema type?

Also, I tried to fallback to the `@sanity/types` Rule export, but it didn't like that either and gave me a sort of cryptic error. 

And lastly, I think using a document defined with `defineField` in Sanity's `defineConfig` isn't working because of the validation bits.

I pulled down the repo and here is an example of a failing test:
```ts
    it("returns the same object as sanity", () => {
      const doc = defineType({
        name: "foo",
        type: "document",
        fields: [
          defineField({
            name: "bar",
            type: "boolean",
          }),
        ],
      });
      const sanityDoc = defineTypeNative({
        name: "foo",
        type: "document",
        fields: [
          defineFieldNative({
            name: "bar",
            type: "boolean",
          }),
        ],
      });
      // passing
      expect(doc).toStrictEqual(sanityDoc);
      // failing
      expectType<typeof doc>().toBeAssignableTo<SchemaTypeDefinition>();
    });
```

Let me know if I can provide any further information, as I would love to help propel this library and use case forward

**Comment by saiichihashimoto** [comment] 2023-06-14 19:19
None of the native methods will return the same types, nor will they likely be assignable to one another. They don't carry enough type information to do the job of this library, so that test failing is working as intended.

Can you give a minimal repro of what you're talking about? All the `validation`'s are producing the correct types as far as I can tell, so it's really hard to see what you're saying.

`defineConfig` doesn't restrict the type of it's input at all, so I can't really see how that's happening.

**Comment by mckelveygreg** [comment] 2023-06-14 19:33
Yeah, I'm getting errors just trying to pass in schemas:
```
const testSchema = defineField({
  name: "test",
  type: "document",
  fields: [
    defineField({
      name: "title",
      type: "string",
    }),
  ],
})

defineConfig({
  schema: {
    types: [testSchema],
  },
})
```
here is a copy of the error:
```
Type 'Omit<{ type: "document"; liveEdit?: boolean | undefined; orderings?: SortOrdering[] | undefined; options?: DocumentOptions | undefined; initialValue?: InitialValueProperty<...>; ... 12 more ...; fields: [...]; } & { ...; }, "preview"> & { ...; } & FieldDefinitionBase & { ...; }' is not assignable to type 'SchemaTypeDefinition'.
  Type 'Omit<{ type: "document"; liveEdit?: boolean | undefined; orderings?: SortOrdering[] | undefined; options?: DocumentOptions | undefined; initialValue?: InitialValueProperty<...>; ... 12 more ...; fields: [...]; } & { ...; }, "preview"> & { ...; } & FieldDefinitionBase & { ...; }' is not assignable to type 'DocumentDefinition'.
    Types of property 'validation' are incompatible.
      Type 'ValidationBuilder<{ title?: string | undefined; _id: string; _type: string; _createdAt: string; _updatedAt: string; _rev: string; }, false, RuleDef<WithValue<{ title?: string | undefined; _id: string; _type: string; _createdAt: string; _updatedAt: string; _rev: string; }>, { ...; }>> | undefined' is not assignable to type 'ValidationBuilder<DocumentRule, SanityDocument> | undefined'.
        Type 'ValidationBuilder<{ title?: string | undefined; _id: string; _type: string; _createdAt: string; _updatedAt: string; _rev: string; }, false, RuleDef<WithValue<{ title?: string | undefined; _id: string; _type: string; _createdAt: string; _updatedAt: string; _rev: string; }>, { ...; }>>' is not assignable to type 'ValidationBuilder<DocumentRule, SanityDocument>'.
          Types of parameters 'rule' and 'rule' are incompatible.
            Property '[requiredSymbol]' is missing in type 'RuleDef<DocumentRule, SanityDocument>' but required in type '{ custom: <LenientFieldValue extends { title?: string | undefined; _id: string; _type: string; _createdAt: string; _updatedAt: string; _rev: string; }>(fn: CustomValidator<LenientFieldValue | undefined>) => WithValue<...>; ... 4 more ...; [requiredSymbol]: false; }'.ts(2322)
index.d.ts(19, 5): '[requiredSymbol]' is declared here.

**Comment by saiichihashimoto** [comment] 2023-06-14 19:59
Ah, I misread the typing on `defineConfig`'s generic. Yes, I do have to fix the typings. For now, you might want to do:

```typescript
defineConfig({
  schema: {
    types: [testSchema as WhateverTypeThisTakes],
  },
})
```

It should all work and you shouldn't lose much here.

**Comment by saiichihashimoto** [comment] 2023-06-14 20:35
ohhhh yeah I definitely cut some corners here. I can get that working too.

**Comment by saiichihashimoto** [comment] 2023-06-14 20:47
#64 should fix your first issue. semantic-release will comment in the PR when the new version releases. You'll have to import `defineConfig` from this library as well now.

**Comment by saiichihashimoto** [comment] 2023-06-14 21:25
And #65 should fix your issue with the rules. I'm going to close this issue. Thanks for your feedback!

**Closed by saiichihashimoto** 2023-06-14 21:25 UTC
Labels: types
