### ISSUE TITLE
String union types

### ISSUE THREAD

**Issue by mckelveygreg** [saiichihashimoto/sanity-typed#123] opened 2023-07-13 21:05 UTC
Couldn't tell if this is possible, but how would I get a string union from a `string` type that has an `options.list` array?

My current work around is to use an enum and then send that along for my frontend to use. 

I looked in to adding it, the test was easy enough to make, but I couldn't figure out where to crack into the system to peel out the values from the `options.list` array 🤷 LMK if I could be of help!

**Comment by saiichihashimoto** [comment] 2023-07-13 21:25
This is a duplicate of #78. I don't have a good answer for this. The tests are relatively easy to add, but most of my attempts to do this haven't worked out well. We had it in the schema-builder but the way those types were constructed were very different, so the strategy that worked there won't work here.

**Closed by saiichihashimoto** 2023-07-13 21:25 UTC
Labels: types

**Comment by mckelveygreg** [comment] 2023-07-13 21:38
Oh, thanks for the link. Yeah, there seemed to be a bit of complexity here...
