### ISSUE TITLE
How to define an array of custom types?

### ISSUE THREAD

**Issue by bo-carey** [saiichihashimoto/sanity-typed#98] opened 2023-06-29 13:31 UTC
I'm trying to create a 'Page Builder' type that takes an array of other custom types ('hero', 'form', etc.). I keep getting errors when trying to configure it and I'm not sure what I'm doing wrong since there isn't an example of this being done in the README. Can anyone give me a pointer? Here is my current solution which results in every type except PageSchemaType to be `never`.

```ts
const hero = defineType({
  name: 'hero',
  type: 'object',
  title: 'Hero',
  fields: [
    defineField({
      name: 'heading',
      type: 'string',
      title: 'Heading',
      validation: (Rule) => Rule.required(),
    })
  ],
});

const form = defineType({
  name: 'form',
  type: 'object',
  title: 'Form',
  fields: [
    defineField({
      name: 'form',
      type: 'string',
      title: 'Form',
      description: 'Select form type',
      options: {
        list: ['newsletter', 'register', 'contact'],
      },
      validation: (Rule) => Rule.required(),
    }),
  ],
});

const page = defineType({
  name: 'page',
  type: 'document',
  title: 'Page',
  fields: [
    defineField({
      name: 'pageBuilder',
      type: 'array',
      title: 'Page builder',
      of: [
        defineField({ type: 'hero', name: 'hero', title: 'Hero' }),
        defineField({ type: 'form', name: 'form', title: 'Form' }),
      ],
    }),
  ],
});

const config = defineConfig({
  // ...
  schema: {
    types: [
      hero,
      form,
      page
    ],
  },
  // ...
});

type Values = InferSchemaValues<typeof config>;
export type PageSchemaType = Extract<Values, { _type: 'page' }>;
export type HeroSchemaType = Extract<Values, { _type: 'hero' }>; // becomes type 'never'
export type FormSchemaType = Extract<Values, { _type: 'form' }>; // becomes type 'never'
```

**Comment by saiichihashimoto** [comment] 2023-06-29 21:04
Technically, `Values` has all three. You can see by inspecting the type of `Exclude<Values, PageSchemaType>`. The issue is that the derived object aren't being given a `_type`. This issue is being addressed in #96, so I'm going to close this so follow this issue there.

**Closed by saiichihashimoto** 2023-06-29 21:04 UTC
Labels: types
